# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on: [push, pull_request]
#   schedule:
#     - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "Github"
      - run: |
              if [[ `npm info firebaseui version` != `npm info firebaseui-id version` ]]
              then 
                git clone --depth=1 --branch v`npm info firebaseui version` https://github.com/firebase/firebaseui-web.git firebaseui-id
                node ./prepare.js
              fi
      - run: cd firebaseui-id && npm ci
      - run: cd firebaseui-id && npm run build
      - run: cd firebaseui-id && npm run build build-js-id && npm run build build-esm-id && npm run build build-npm-id
      - run: cd firebaseui-id && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: cd firebaseui-id && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
